device: 0 # cuda device to use, i.e. 0 or 0,1,2,3 or cpu'
method: model_doctor
model_name: resnet
model_depth: 34
n_channels: 1
n_classes: 4
load_model: /nfs3-p2/zsxm/temp_path/3d81.pth
epochs: 50
early_stopping: 0
batch_size: 128
optimizer: rmsprop
lr: 0.0001 # learning rate
val_percent: 0.2 # Part of the data that is used as validation (0.0-1.0)
img_size: 81
save_cp: false # whether save checkpoints
load_optim: false # load optimizer from .pth file
load_scheduler: false # load scheduler from .pth file
dir_img: /nfs3-p1/zsxm/dataset/aorta_classify_ct_-100_500/center
info: model docter 3d,使用绝对值梯度，使用通道和空间约束，通道约束只用在最后一个卷积，增加layer2和layer3的空间约束，继续训练，通道系数设为3e10，空间系数设为8e9
flag_3d: true
depth_3d: 7
step_3d: 1
residual_3d: false
norm_encoder_output: true
which_supcon: last
classifier_epochs: 20
classifier_batch_size: 128
classifier_lr: 0.0001
temperature: 0.1
load_encoder: false #details/checkpoints/SupCon/11-12_13:40:42/Net_last.pth
entire: true
alpha: 0.3
noise: false