device: 1 # cuda device to use, i.e. 0 or 0,1,2,3 or cpu'
method: ce
model_depth: 34
n_channels: 1
n_classes: 4
load_model: false # initial weights path, "false" means not load model weight
epochs: 100
early_stopping: 0
batch_size: 128
optimizer: RMSprop
lr: 0.0001 # learning rate
val_percent: 0.2 # Part of the data that is used as validation (0.0-1.0)
img_size: 81
save_cp: false # whether save checkpoints
load_optim: false # load optimizer from .pth file
load_scheduler: false # load scheduler from .pth file
dir_img: /nfs3-p1/zsxm/dataset/aorta_classify_ct_-100_500/
info: 增加了浙江医院的数据集后,EfficientNet-B3
flag_3d: false
depth_3d: 7
step_3d: 1
residual_3d: false
norm_encoder_output: true
which_supcon: last
classifier_epochs: 20
classifier_batch_size: 128
classifier_lr: 0.0001
temperature: 0.1
load_encoder: false #details/checkpoints/SupCon/11-12_13:40:42/Net_last.pth
entire: true
alpha: 0.3
